version: '2'

services:
    web:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./code:/code
            - ./site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network
    php:
        build: 
            context: ./
            dockerfile: php-docker.dockerfile
        volumes:
            - ./code:/code
        networks:
            - code-network
    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - "3307:3306"
        volumes:
            - db_data:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: admin
        networks:
            - code-network
    phpMyAdmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8081:80"
        environment: 
            PMA_HOST: db
            PMA_USER: root
            PMA_PASSWORD: admin
        networks:
            - code-network

networks:
    code-network:
        driver: bridge
volumes:
    db_data: